### ISSUE TITLE
node >= 9.0.0

### ISSUE THREAD

**Issue by aleksandrlat** [wessberg/scroll-behavior-polyfill#3]
Hey Frederik!
I have question about this node version requirement:
https://github.com/wessberg/scroll-behavior-polyfill/blob/master/package.json#L66

Is it really required? I'm curious if transpiled/compiled package can be used with other node versions.
I have tried it and it works well with 8.12.0 version. We have 8.12.0 node version in our package.json

I had to install package with `--ignore-engines` yarn flag on my dev env
`yarn add scroll-behavior-polyfill --dev --ignore-engines`

But this blocks me from using your package on prod build. Can you reduce node version?

**Comment by wessberg** [comment]
Hi there. Thanks for making me aware of this issue. Node >= 9.0.0 is definitely *not* required. I've fixed this and published a new version (v2.0.4).

Best regards

**Comment by aleksandrlat** [comment]
Awesome man! Thanks!
