### ISSUE TITLE
Issue with dynamic import: "'index.d.ts' is not a module"

### ISSUE THREAD

**Issue by ladvoc** [wessberg/scroll-behavior-polyfill#8]
Hello. I have installed the library and dynamically import it when required. However, I receive the following error:
```
File '/path/to/project/node_modules/scroll-behavior-polyfill/dist/index.d.ts' is not a module.
```
Since `index.d.ts` clearly exists at that location, I assume there is something wrong with my TypeScript configuration. I cannot seem to find an option which fixes the issue. Any ideas?

My current `tsconfig.json` file:
```json
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "allowUnreachableCode": false,
        "declaration": false,
        "experimentalDecorators": true,
        "lib": [
            "dom",
            "es2015"
        ],
        "moduleResolution": "node",
        "module": "esnext",
        "target": "es2017",
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "jsx": "react",
        "jsxFactory": "h"
    },
    "include": [
        "src"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

Thank you for you assistance.

**Comment by wessberg** [comment]
Hi there. Thanks for reporting this issue. I've fixed it in the latest release (v2.0.11) (by marking the declaration file as a module).
