### ISSUE TITLE
anchor detection if the link also contains a path fails

### ISSUE THREAD

**Issue by Nemo64** [wessberg/scroll-behavior-polyfill#9]
https://github.com/wessberg/scroll-behavior-polyfill/blob/45593dcfc35f98b64230579eb01ac821c5d9f67d/src/patch/anchor/catch-navigation.ts

The catch-navigation currently looks if a link is clicked with `href="#anchor"` but it will never catch a link to the current page using `href="/url/to/current/page#anchor"` because only the attribute value is considered and only if it contains nothing else.

The detection for a link pointing to the current page is actually fairly simple:

```Javascript
const link = e.target;
const pointsToCurrentPage =
       link.origin === location.origin
    && link.pathname === location.pathname
    && link.search === location.search;

const hash = link.hash
```

Here is a reproduction: https://jsfiddle.net/ey087v3o/ (tested in safari and chrome)

**Comment by wessberg** [comment]
Hey there. Thanks a lot for your bug report and repro. This has been fixed in the latest release (v2.0.12). I took great inspiration from your detection, thanks a lot.
